/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prevent_segmentetion;

import java.io.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import prevent_segmentetion.admin.Login;

/**
 * User Login Screen
 * @author rana
 */
public class login_Screen extends javax.swing.JFrame {

    
    private String folder_name = null;
    beanClass obj_beanClass = new beanClass();
    String separator=System.getProperty("file.separator");
    
    String homeDir;
    
    String path_File = homeDir;
    String full_path;
    String path_file_used_by_browse = homeDir;
    File file_open;

    /**
     * Creates new form login_Screen
     */
    public login_Screen() {
        initComponents();
        homeDir=System.getProperty("user.home")+separator+"project_segmentation"+separator;
        full_path=homeDir;
        path_file_used_by_browse=homeDir;
        file_open=new File(homeDir);
        
//        preferences=Preferences.userNodeForPackage(prevent_segmentetion.login_Screen.class);
        

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
        hideLayeredPanes();
        jPanel_loginScreen.setVisible(true);
//        jPanel1_loginScreen.setSize(366, 358);

        jPanel_userFrontEnd.setVisible(false);
        jButton2_Upload.setEnabled(false);
        this.setSize(366, 224);
        jButton_userFront_Download.setEnabled(false);
    }

    
    /**
     * Hides all Layered Panes
     */
    public void hideLayeredPanes() {
        jPanel_Edit_Profile.setVisible(false);
        jPanel_loginScreen.setVisible(false);
        jPanel_userFrontEnd.setVisible(false);

    }

    
    /**
     * Deprecated Not in Use
     */
    public void textField_txt_read() {
        //    if()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jPanel_loginScreen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton_Login = new javax.swing.JButton();
        jTextField1_username = new javax.swing.JTextField();
        jPasswordField1_Password = new javax.swing.JPasswordField();
        lbl_LginStatus = new javax.swing.JLabel();
        jPanel_userFrontEnd = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_Firstname = new javax.swing.JLabel();
        lbl_lastname = new javax.swing.JLabel();
        lbl_Address = new javax.swing.JLabel();
        lbl_City = new javax.swing.JLabel();
        lbl_country = new javax.swing.JLabel();
        lbl_Pincode = new javax.swing.JLabel();
        lbl_Mobile = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        jButton1_Browse = new javax.swing.JButton();
        jButton2_Upload = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton_userFront_Download = new javax.swing.JButton();
        jPanel_Edit_Profile = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField_EditPane_Username = new javax.swing.JTextField();
        jTextField_EditPane_Password = new javax.swing.JTextField();
        jTextField_EditPane_FirstName = new javax.swing.JTextField();
        jTextField_EditPane_LastName = new javax.swing.JTextField();
        jTextField_EditPane_Email = new javax.swing.JTextField();
        jTextField_EditPane_Mobie = new javax.swing.JTextField();
        jTextField_EditPane_City = new javax.swing.JTextField();
        jTextField_EditPane_Pincode = new javax.swing.JTextField();
        jTextField_EditPane_Country = new javax.swing.JTextField();
        jTextField_EditPane_Address = new javax.swing.JTextField();
        jTextField_Retype_Password = new javax.swing.JTextField();
        jButton_EditPane_Apply = new javax.swing.JButton();
        jButton_EditPane_Cancel = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel_EditPane_LoginStatus_Status = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu_User = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem_Login = new javax.swing.JMenuItem();
        jMenu_Help = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_loginScreen.setForeground(new java.awt.Color(32, 188, 249));

        jLabel1.setText("Enter your Username and Password Here :");

        jLabel2.setText("Username :");

        jLabel3.setText("Password :");

        jButton_Login.setBackground(new java.awt.Color(152, 229, 255));
        jButton_Login.setForeground(new java.awt.Color(36, 182, 222));
        jButton_Login.setText("Login");
        jButton_Login.setPreferredSize(new java.awt.Dimension(100, 27));
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });

        jTextField1_username.setPreferredSize(new java.awt.Dimension(150, 27));

        jPasswordField1_Password.setPreferredSize(new java.awt.Dimension(150, 27));

        lbl_LginStatus.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        lbl_LginStatus.setForeground(new java.awt.Color(250, 11, 20));
        lbl_LginStatus.setText("                               ");

        javax.swing.GroupLayout jPanel_loginScreenLayout = new javax.swing.GroupLayout(jPanel_loginScreen);
        jPanel_loginScreen.setLayout(jPanel_loginScreenLayout);
        jPanel_loginScreenLayout.setHorizontalGroup(
            jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                        .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1_Password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_LginStatus))
        );
        jPanel_loginScreenLayout.setVerticalGroup(
            jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_loginScreenLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel_loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_LginStatus))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel_userFrontEnd.setBackground(new java.awt.Color(0, 224, 255));
        jPanel_userFrontEnd.setForeground(new java.awt.Color(7, 141, 181));
        jPanel_userFrontEnd.setName("User Profile : "+obj_beanClass.getVarUsername());

        jTree1.setBackground(new java.awt.Color(0, 252, 255));
        jTree1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTree1.setForeground(new java.awt.Color(5, 91, 132));
        jTree1.setToolTipText("File Explorer");
        jTree1.setAutoscrolls(true);
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jTextArea1.setBackground(new java.awt.Color(253, 244, 194));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(216, 133, 2));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setText("Logged in User Details  :");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 131, 3));
        jLabel5.setText("Username      :");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(38, 131, 3));
        jLabel6.setText("First Name    :");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(38, 131, 3));
        jLabel7.setText("Last Name     :");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(38, 131, 3));
        jLabel8.setText("Address        :");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(38, 131, 3));
        jLabel9.setText("City             :");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(38, 131, 3));
        jLabel10.setText("Country         :");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(38, 131, 3));
        jLabel11.setText("Pin Code        :");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(38, 131, 3));
        jLabel12.setText("Mobile No      :");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(38, 131, 3));
        jLabel13.setText("E-Mail            :");

        lbl_username.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(38, 131, 3));
        lbl_username.setText("lbl_username");

        lbl_Firstname.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl_Firstname.setForeground(new java.awt.Color(38, 131, 3));
        lbl_Firstname.setText("lbl_FirstName");

        lbl_lastname.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl_lastname.setForeground(new java.awt.Color(38, 131, 3));
        lbl_lastname.setText("lbl_Lastname");

        lbl_Address.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl_Address.setForeground(new java.awt.Color(38, 131, 3));
        lbl_Address.setText("lbl_Address");

        lbl_City.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl_City.setForeground(new java.awt.Color(38, 131, 3));
        lbl_City.setText("lbl_City");

        lbl_country.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl_country.setForeground(new java.awt.Color(38, 131, 3));
        lbl_country.setText("lbl_Country");

        lbl_Pincode.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl_Pincode.setForeground(new java.awt.Color(38, 131, 3));
        lbl_Pincode.setText("lbl_Pincode");

        lbl_Mobile.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl_Mobile.setForeground(new java.awt.Color(38, 131, 3));
        lbl_Mobile.setText("lbl_Mobile");

        lbl_Email.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(38, 131, 3));
        lbl_Email.setText("lbl_Email");

        jButton1_Browse.setBackground(new java.awt.Color(173, 247, 174));
        jButton1_Browse.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton1_Browse.setForeground(new java.awt.Color(2, 143, 28));
        jButton1_Browse.setText("Browse");
        jButton1_Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_BrowseActionPerformed(evt);
            }
        });

        jButton2_Upload.setBackground(new java.awt.Color(152, 254, 132));
        jButton2_Upload.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton2_Upload.setForeground(new java.awt.Color(15, 139, 28));
        jButton2_Upload.setText("Upload");
        jButton2_Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_UploadActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Refresh File Explorer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton_userFront_Download.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton_userFront_Download.setText("Download");
        jButton_userFront_Download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_userFront_DownloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_userFrontEndLayout = new javax.swing.GroupLayout(jPanel_userFrontEnd);
        jPanel_userFrontEnd.setLayout(jPanel_userFrontEndLayout);
        jPanel_userFrontEndLayout.setHorizontalGroup(
            jPanel_userFrontEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userFrontEndLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_userFrontEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_userFrontEndLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_userFront_Download, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel_userFrontEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_userFrontEndLayout.createSequentialGroup()
                        .addComponent(jButton1_Browse, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton2_Upload, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel_userFrontEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_userFrontEndLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel_userFrontEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel_userFrontEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_username, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Email)
                            .addComponent(lbl_Mobile)
                            .addComponent(lbl_Pincode)
                            .addComponent(lbl_country)
                            .addComponent(lbl_City)
                            .addComponent(lbl_Address)
                            .addComponent(lbl_lastname)
                            .addComponent(lbl_Firstname)))
                    .addGroup(jPanel_userFrontEndLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)))
                .addGap(65, 65, 65))
        );
        jPanel_userFrontEndLayout.setVerticalGroup(
            jPanel_userFrontEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_userFrontEndLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_userFrontEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_userFrontEndLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_userFrontEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_userFrontEndLayout.createSequentialGroup()
                                .addComponent(lbl_username)
                                .addGap(26, 26, 26)
                                .addComponent(lbl_Firstname)
                                .addGap(26, 26, 26)
                                .addComponent(lbl_lastname)
                                .addGap(27, 27, 27)
                                .addComponent(lbl_Address)
                                .addGap(27, 27, 27)
                                .addComponent(lbl_City)
                                .addGap(26, 26, 26)
                                .addComponent(lbl_country)
                                .addGap(24, 24, 24)
                                .addComponent(lbl_Pincode)
                                .addGap(27, 27, 27)
                                .addComponent(lbl_Mobile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_Email))
                            .addGroup(jPanel_userFrontEndLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel8)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel11)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_userFrontEndLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel_userFrontEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2_Upload)
                            .addComponent(jButton1_Browse))
                        .addGap(178, 178, 178))
                    .addGroup(jPanel_userFrontEndLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(jPanel_userFrontEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_userFront_Download, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))))
        );

        jPanel_Edit_Profile.setBackground(new java.awt.Color(255, 255, 204));
        jPanel_Edit_Profile.setForeground(new java.awt.Color(204, 255, 255));

        jLabel14.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel14.setText("Edit Profile :");

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Username :");

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Password :");

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("First Name :");

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Last Name :");

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("E-mail :");

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 102));
        jLabel20.setText("City :");

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 102));
        jLabel21.setText("Mobile :");

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 102));
        jLabel22.setText("Country :");

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 102));
        jLabel23.setText("Pincode :");

        jTextField_EditPane_Username.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField_EditPane_Username.setPreferredSize(new java.awt.Dimension(240, 33));

        jTextField_EditPane_Password.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField_EditPane_Password.setPreferredSize(new java.awt.Dimension(240, 33));

        jTextField_EditPane_FirstName.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField_EditPane_FirstName.setPreferredSize(new java.awt.Dimension(240, 33));

        jTextField_EditPane_LastName.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField_EditPane_LastName.setPreferredSize(new java.awt.Dimension(240, 33));

        jTextField_EditPane_Email.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField_EditPane_Email.setPreferredSize(new java.awt.Dimension(240, 33));

        jTextField_EditPane_Mobie.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField_EditPane_Mobie.setPreferredSize(new java.awt.Dimension(240, 33));

        jTextField_EditPane_City.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField_EditPane_City.setPreferredSize(new java.awt.Dimension(240, 33));

        jTextField_EditPane_Pincode.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField_EditPane_Pincode.setPreferredSize(new java.awt.Dimension(240, 33));

        jTextField_EditPane_Country.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField_EditPane_Country.setPreferredSize(new java.awt.Dimension(240, 33));

        jTextField_EditPane_Address.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField_EditPane_Address.setPreferredSize(new java.awt.Dimension(240, 33));

        jTextField_Retype_Password.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextField_Retype_Password.setPreferredSize(new java.awt.Dimension(240, 33));

        jButton_EditPane_Apply.setBackground(new java.awt.Color(204, 255, 204));
        jButton_EditPane_Apply.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton_EditPane_Apply.setForeground(new java.awt.Color(0, 102, 0));
        jButton_EditPane_Apply.setText("Apply");
        jButton_EditPane_Apply.setPreferredSize(new java.awt.Dimension(200, 35));
        jButton_EditPane_Apply.setVerifyInputWhenFocusTarget(false);
        jButton_EditPane_Apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditPane_ApplyActionPerformed(evt);
            }
        });

        jButton_EditPane_Cancel.setBackground(new java.awt.Color(204, 255, 204));
        jButton_EditPane_Cancel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton_EditPane_Cancel.setForeground(new java.awt.Color(0, 102, 0));
        jButton_EditPane_Cancel.setText("Cancel");
        jButton_EditPane_Cancel.setPreferredSize(new java.awt.Dimension(200, 35));
        jButton_EditPane_Cancel.setVerifyInputWhenFocusTarget(false);
        jButton_EditPane_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditPane_CancelActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 102));
        jLabel25.setText("Re-Type Password :");

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("Address :");

        jLabel_EditPane_LoginStatus_Status.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel_EditPane_LoginStatus_Status.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel_Edit_ProfileLayout = new javax.swing.GroupLayout(jPanel_Edit_Profile);
        jPanel_Edit_Profile.setLayout(jPanel_Edit_ProfileLayout);
        jPanel_Edit_ProfileLayout.setHorizontalGroup(
            jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Edit_ProfileLayout.createSequentialGroup()
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_Edit_ProfileLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(jPanel_Edit_ProfileLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel14))
                            .addGroup(jPanel_Edit_ProfileLayout.createSequentialGroup()
                                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel15)
                                    .addComponent(jButton_EditPane_Apply, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel25))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_EditPane_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField_EditPane_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_EditPane_Mobie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_EditPane_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_EditPane_Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_EditPane_Pincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_EditPane_Password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_EditPane_Username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_EditPane_FirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_EditPane_LastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_Retype_Password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_EditPane_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel_Edit_ProfileLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel_EditPane_LoginStatus_Status)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Edit_ProfileLayout.setVerticalGroup(
            jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Edit_ProfileLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel_EditPane_LoginStatus_Status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_EditPane_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_EditPane_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Retype_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField_EditPane_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField_EditPane_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField_EditPane_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField_EditPane_Mobie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField_EditPane_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField_EditPane_City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField_EditPane_Country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField_EditPane_Pincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel_Edit_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_EditPane_Apply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_EditPane_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        jMenuBar2.setBackground(new java.awt.Color(0, 51, 51));
        jMenuBar2.setBorder(null);
        jMenuBar2.setForeground(new java.awt.Color(0, 51, 51));
        jMenuBar2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jMenu_User.setText("User");
        jMenu_User.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jMenuItem4.setText("Admin Login");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu_User.add(jMenuItem4);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jMenuItem3.setText("Profile Edit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu_User.add(jMenuItem3);

        jMenuItem_Login.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem_Login.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jMenuItem_Login.setText("Log Out");
        jMenuItem_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LoginActionPerformed(evt);
            }
        });
        jMenu_User.add(jMenuItem_Login);

        jMenuBar2.add(jMenu_User);

        jMenu_Help.setText("Help");
        jMenu_Help.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jMenuItem2.setText("Help");
        jMenu_Help.add(jMenuItem2);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jMenuItem1.setText("About Us");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu_Help.add(jMenuItem1);

        jMenuBar2.add(jMenu_Help);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_loginScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(964, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel_userFrontEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Edit_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_loginScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(454, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_userFrontEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_Edit_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * Login action performed ; Iser name Password Validation 
     * Retrieves User details
     * @param evt 
     */
    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed

        try {
            obj_beanClass = new beanClass();

            String varQuery = "SELECT * FROM PROFILE WHERE USERNAME='" + jTextField1_username.getText() + "'";
            ResultSet rst = new DBHelper().getSt().executeQuery(varQuery);
            obj_beanClass.setVarUsername(jTextField1_username.getText());
            obj_beanClass.setVarPassword(String.valueOf(jPasswordField1_Password.getPassword()));

            if ((!jTextField1_username.equals("")) && (!obj_beanClass.getVarPassword().equals(""))) {

                while (rst.next()) {

                    if ((rst.getString("USERNAME").equals(obj_beanClass.getVarUsername())) && (rst.getString("PASSWORD").equals(obj_beanClass.getVarPassword()))) {
                        obj_beanClass.setVarAddress(rst.getString("ADDRESS"));
                        obj_beanClass.setVarCity(rst.getString("CITY"));
                        obj_beanClass.setVarCountry(rst.getString("COUNTRY"));
                        obj_beanClass.setVarEmail(rst.getString("EMAIL"));
                        obj_beanClass.setVarFirst_name(rst.getString("FIRST_NAME"));
                        obj_beanClass.setVarLast_name(rst.getString("LAST_NAME"));
                        obj_beanClass.setVarMobile(rst.getString("MOBILE"));
                        obj_beanClass.setVarPincode(rst.getString("PINCODE"));
                        obj_beanClass.setVarUsername(rst.getString("USERNAME"));

                        jPanel_userFrontEnd.setVisible(true);
                        jPanel_loginScreen.setVisible(false);

                        lbl_Address.setText(obj_beanClass.getVarAddress());
                        lbl_City.setText(obj_beanClass.getVarCity());
                        lbl_Email.setText(obj_beanClass.getVarEmail());
                        lbl_Mobile.setText(obj_beanClass.getVarMobile());
                        lbl_country.setText(obj_beanClass.getVarCountry());
                        lbl_lastname.setText(obj_beanClass.getVarLast_name());
                        lbl_username.setText(obj_beanClass.getVarUsername());
                        lbl_Firstname.setText(obj_beanClass.getVarFirst_name());
                        lbl_Pincode.setText(obj_beanClass.getVarPincode());

                        tree_Function();
                        this.setResizable(true);
                        this.setExtendedState(MAXIMIZED_BOTH);

                    } else {
                        JOptionPane.showMessageDialog(null, "Wrong Username or Password");

                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Username & Password field can't be Empty.");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_jButton_LoginActionPerformed

    
    /**
     * Initializes About Us screen Object
     * @param evt 
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        About_Us us=new About_Us(this, rootPaneCheckingEnabled);
        us.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    
    /**
     * instantiates DBHelper Class OBject
     * and Retrieves data from that Object 
     * 
     * @param evt 
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            // TODO add your handling code here:
            hideLayeredPanes();
            DBHelper help = new DBHelper();
            ResultSet rst = help.st.executeQuery("select * from PROFILE where USERNAME='" + obj_beanClass.getVarUsername() + "'");
            while (rst.next()) {
                jTextField_EditPane_Username.setText(obj_beanClass.getVarUsername());
                jTextField_EditPane_Password.setText(obj_beanClass.getVarPassword());
                jTextField_EditPane_City.setText(obj_beanClass.getVarCity());
                jTextField_EditPane_Country.setText(obj_beanClass.getVarCountry());
                jTextField_EditPane_Email.setText(obj_beanClass.getVarEmail());
                jTextField_EditPane_FirstName.setText(obj_beanClass.getVarFirst_name());
                jTextField_EditPane_LastName.setText(obj_beanClass.getVarLast_name());
                jTextField_EditPane_Pincode.setText(obj_beanClass.getVarPincode());
                jTextField_EditPane_Mobie.setText(obj_beanClass.getVarMobile());
                jTextField_EditPane_Address.setText(obj_beanClass.getVarAddress());
            }
            jTextField_EditPane_Email.setEnabled(false);
            jTextField_EditPane_Username.setEnabled(false);

            jPanel_Edit_Profile.setVisible(true);

        } catch (SQLException ex) {
            Logger.getLogger(login_Screen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    
    
    
    /**
     * Updates current users details
     * @param evt 
     */
    private void jButton_EditPane_ApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditPane_ApplyActionPerformed

        String EditStatus = null;
        try {
            // TODO add your handling code here:
            DBHelper help = new DBHelper();
            String pass1 = jTextField_EditPane_Password.getText();
            String pass2 = jTextField_Retype_Password.getText();

            if (pass1.equals(pass2)) {
                int i = help.st.executeUpdate("UPDATE pre_seg.PROFILE SET `PASSWORD` = '" + jTextField_EditPane_Password.getText() + "', `ADDRESS` = '" + jTextField_EditPane_Address.getText() + "', `CITY` = '" + jTextField_EditPane_City.getText() + "', `COUNTRY` = '" + jTextField_EditPane_Country.getText() + "', `EMAIL` = '" + jTextField_EditPane_Email.getText() + "', `FIRST_NAME` = '" + jTextField_EditPane_FirstName.getText() + "', `LAST_NAME` = '" + jTextField_EditPane_LastName.getText() + "', `MOBILE` = '" + jTextField_EditPane_Mobie.getText() + "', `PINCODE` = '" + jTextField_EditPane_Pincode.getText() + "' WHERE USERNAME = '" + obj_beanClass.getVarUsername() + "'");
                //UPDATE pre_seg.PROFILE SET `USERNAME` = 'vivekc', `PASSWORD` = 'vivekc', `ADDRESS` = 'Noorpurc', `CITY` = 'c', `COUNTRY` = 'Indiac', `EMAIL` = 'vivek@gmail.comc', `FIRST_NAME` = 'Vivekc', `LAST_NAME` = 'Ranac', `MOBILE` = '+91-8449587008c', `PINCODE` = '203202c' WHERE USERNAME = 'vivek';
                jPanel_Edit_Profile.setVisible(false);
                jPanel_userFrontEnd.setVisible(true);

            } else {
                EditStatus = "Password Mismatch! Retry !";

            }
            jLabel_EditPane_LoginStatus_Status.setText(EditStatus);

        } catch (SQLException ex) {
            Logger.getLogger(login_Screen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_EditPane_ApplyActionPerformed

    
    /**
     * makes Visible Edit Profile 
     * and User front end
     * @param evt 
     */
    private void jButton_EditPane_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditPane_CancelActionPerformed
        // TODO add your handling code here:
        jPanel_Edit_Profile.setVisible(false);
        jPanel_userFrontEnd.setVisible(true);
    }//GEN-LAST:event_jButton_EditPane_CancelActionPerformed

    
    /**
     * Calls tree_function
     */
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tree_Function();
        jButton_userFront_Download.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * Used to upload files 
     * @param evt 
     */
    private void jButton2_UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_UploadActionPerformed
        File file_upload = new File(path_file_used_by_browse);

        //        System.out.println("path"+file_upload);
        if (file_upload.toString().toUpperCase().endsWith("DOCX") || file_upload.toString().toUpperCase().endsWith("DOC")) {
            folder_name = "DOCX";
        } else {
            if (file_upload.toString().toUpperCase().endsWith("TXT")) {
                folder_name = "TXT";
            } else {
                if (file_upload.toString().toUpperCase().endsWith("XLSX") || file_upload.toString().toUpperCase().endsWith("XLSX")) {
                    folder_name = "XLSX";
                } else {
                    if (file_upload.toString().toUpperCase().endsWith("PPTX") || file_upload.toString().toUpperCase().endsWith("PPT")) {
                        folder_name = "PPTX";
                    } else {
                        JOptionPane.showMessageDialog(null, "Files other than Docx,TXT,XLSX,PPTX are not allowed to upload");
                        folder_name = null;

                    }
                }
            }

        }
        /**
         * file_name is the name of variable that we are uploading; to the
         * server
         */
        if (!folder_name.equals(null)) {
            String file_name = file_upload.getName();

            File target = new File(homeDir + obj_beanClass.getVarUsername() + "/" + folder_name + "/" + file_name);

            try {

                Files.copy(file_upload.toPath(), target.toPath(), REPLACE_EXISTING);
                JOptionPane.showMessageDialog(null, "File Uploaded Successfully!" + " to " + folder_name);

            } catch (IOException ex) {

                JOptionPane.showMessageDialog(null, ex);

            }
        }

        jButton2_Upload.setEnabled(false);
    }//GEN-LAST:event_jButton2_UploadActionPerformed

    
    
    /**
     * Browse Button Action performed Here
     * @param evt 
     */
    private void jButton1_BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_BrowseActionPerformed

        JFileChooser obj_FileChooser = new JFileChooser();
        int i = obj_FileChooser.showOpenDialog(obj_FileChooser);
        if (i == JFileChooser.APPROVE_OPTION) {
            File f = obj_FileChooser.getSelectedFile();
            path_file_used_by_browse = f.getPath();
            jButton2_Upload.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1_BrowseActionPerformed

    
    /**
     * Deprecated
     * @param evt 
     */
    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTree1ValueChanged

    
    /**
     * Instantiate Prevent Segmentation after Logout
     * @param evt 
     */
    private void jMenuItem_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LoginActionPerformed
        // TODO add your handling code here:
        Prevent_Segmentetion preSeg = new Prevent_Segmentetion();

        preSeg.loginStart();
        this.dispose();
    }//GEN-LAST:event_jMenuItem_LoginActionPerformed

    
    /**
     * User Front End Download Action Performed here
     * @param evt 
     */
    private void jButton_userFront_DownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_userFront_DownloadActionPerformed
        // TODO add your handling code here:
//JOptionPane.showMessageDialog(rootPane, file_open);

        JFileChooser chooseFile = new JFileChooser();
        chooseFile.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooseFile.setDialogTitle("Select a Folder to Download the selected File.");
        int i = chooseFile.showSaveDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {

            File targetSave = new File(chooseFile.getSelectedFile().toString() + "/" + file_open.getName());

            try {
                Files.copy(file_open.toPath(), targetSave.toPath(), REPLACE_EXISTING);
                JOptionPane.showMessageDialog(rootPane, "File Downloaded! to Folder" + targetSave);
                jButton_userFront_Download.setEnabled(false);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, ex);
                jButton_userFront_Download.setEnabled(false);
            }
        }

    }//GEN-LAST:event_jButton_userFront_DownloadActionPerformed

    
    /**
     * Instantiate Admin Login Screen
     * @param evt 
     */
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new login_Screen().setVisible(true);
            }
        });
    }

    /**
     * Jtree Model Implemented on JTree inside Detail panel Contains root and
     * information about the Userdata
     */
    private void tree_Function() {

        DefaultMutableTreeNode node = new DefaultMutableTreeNode(obj_beanClass.getVarUsername());
        File file = new File(homeDir + obj_beanClass.getVarUsername());
        File[] f_arr = file.listFiles();
        for (File f : f_arr) {
            if (f.isDirectory()) {
                File z_file = new File(f.getPath());
                File[] z_arr = z_file.listFiles();
                DefaultMutableTreeNode subnode = new DefaultMutableTreeNode(f.getName());

                node.add(subnode);
                call_itself_Make_dir(f, subnode);
//               

            }
        }

        jTree1.setModel(new DefaultTreeModel(node));
        jTree1.addTreeSelectionListener(new TreeSelectionListener() {

            @Override
            public void valueChanged(TreeSelectionEvent e) {
                //  InputStreamReader isr;
                FileReader fr;
                String h;
                BufferedReader br = null;
                StringBuilder sw = new StringBuilder();
                BufferedWriter bw = null;
                try {
                    h = e.getPath().toString().replace("[", "");
                    h = h.replace("]", "");
                    h = h.replace(", ", "/");
                   
                    full_path = homeDir + h;

                    file_open = new File(full_path);

                    if (file_open.isDirectory()) {
                    } else {
                        jButton_userFront_Download.setEnabled(true);
                        if (file_open.toString().endsWith("txt")) {
                            if (file_open.toString().endsWith(".txt~")) {

                            } else {

                                fr = new FileReader(file_open);

                                BufferedReader br1 = new BufferedReader(fr);

                                int i = 0;
                                String str;

                                while ((str = br1.readLine()) != null) {
                                    sw.append(str).append("\n");

                                }
                                try {
                                    br1.close();
                                    fr.close();
                                } catch (IOException exc) {
                                    JOptionPane.showMessageDialog(null, exc);
                                }
                            }
                        } else {

                        }
                        jTextArea1.setText(" ");
                        jTextArea1.setText(sw.toString());
                    }
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                } finally {
                }
            }
        });

    }

    /**
     * Thefunction Calls itself and add directories to the Node.
     *
     *
     *
     * @param x
     * @param dmtn
     * @return
     */
    public File call_itself_Make_dir(File x, DefaultMutableTreeNode dmtn) {
        if (x.isDirectory()) {

            File f_add = new File(x.getPath());
            File[] f_a = f_add.listFiles();
            for (File y : f_a) {
                DefaultMutableTreeNode treeExpand = new DefaultMutableTreeNode(y.getName());
                dmtn.add(treeExpand);
                call_itself_Make_dir(y, treeExpand);
            }
        }

        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_Browse;
    private javax.swing.JButton jButton2_Upload;
    private javax.swing.JButton jButton_EditPane_Apply;
    private javax.swing.JButton jButton_EditPane_Cancel;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JButton jButton_userFront_Download;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_EditPane_LoginStatus_Status;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem_Login;
    private javax.swing.JMenu jMenu_Help;
    private javax.swing.JMenu jMenu_User;
    private javax.swing.JPanel jPanel_Edit_Profile;
    private javax.swing.JPanel jPanel_loginScreen;
    private javax.swing.JPanel jPanel_userFrontEnd;
    private javax.swing.JPasswordField jPasswordField1_Password;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1_username;
    private javax.swing.JTextField jTextField_EditPane_Address;
    private javax.swing.JTextField jTextField_EditPane_City;
    private javax.swing.JTextField jTextField_EditPane_Country;
    private javax.swing.JTextField jTextField_EditPane_Email;
    private javax.swing.JTextField jTextField_EditPane_FirstName;
    private javax.swing.JTextField jTextField_EditPane_LastName;
    private javax.swing.JTextField jTextField_EditPane_Mobie;
    private javax.swing.JTextField jTextField_EditPane_Password;
    private javax.swing.JTextField jTextField_EditPane_Pincode;
    private javax.swing.JTextField jTextField_EditPane_Username;
    private javax.swing.JTextField jTextField_Retype_Password;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lbl_Address;
    private javax.swing.JLabel lbl_City;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Firstname;
    private javax.swing.JLabel lbl_LginStatus;
    private javax.swing.JLabel lbl_Mobile;
    private javax.swing.JLabel lbl_Pincode;
    private javax.swing.JLabel lbl_country;
    private javax.swing.JLabel lbl_lastname;
    private javax.swing.JLabel lbl_username;
    // End of variables declaration//GEN-END:variables
}
